version: '3'
services:
  plex:
    container_name: plex
    image: linuxserver/plex
    network_mode: host
    restart: unless-stopped
    volumes:
      - plexconfig:/config
      - tv:/tv
      - films:/films
      - music:/music
      - transcode:/transcode

  sonarr:
    container_name: tv
    image: linuxserver/sonarr
    restart: unless-stopped
    volumes:
      - sonarrconfig:/config
      - tv:/tv
    labels:
      - traefik.port=8989
    environment:
      - PUID=0
      - PGID=0
      - UMASK_SET=022

  radarr:
    container_name: film
    image: linuxserver/radarr
    restart: unless-stopped
    volumes:
      - plexconfig:/config
      - films:/films
    labels:
      - traefik.port=7878
    environment:
      - PUID=0
      - PGID=0
      - UMASK_SET=022

  lidarr:
    container_name: music
    image: linuxserver/lidarr
    restart: unless-stopped
    volumes:
      - radarrconfig:/config
      - music:/music
    labels:
      - traefik.port=8686
    environment:
      - PUID=0
      - PGID=0
      - UMASK_SET=022

  jackett:
    container_name: source
    image: linuxserver/jackett
    restart: unless-stopped
    volumes:
      - jackettconfig:/config
    labels:
      - traefik.port=9117

  qbittorrent:
    container_name: torrent
    image: linuxserver/qbittorrent
    restart: unless-stopped
    volumes:
      - qbittorrentconfig:/config
      - tv:/tv
      - films:/films
      - music:/music
    environment:
      - WEBUI_PORT=8080 #admin/adminadmin
    ports:
      - 6881:6881
      - 6881:6881/udp
    labels:
      - traefik.port=8080

  traefik:
    container_name: traefik
    image: "traefik"
    restart: unless-stopped
    volumes:
        - "/var/run/docker.sock:/var/run/docker.sock:ro"
    ports:
      - 80:80
      - 443:443
      - 8080:8080
    command:
      - --debug=false
      - --logLevel=ERROR
      - --defaultentrypoints=https,http
      - --entryPoints=Name:http Address::80 Redirect.EntryPoint:https
      - --entryPoints=Name:https Address::443 TLS
      - --retry
      - --docker.endpoint=unix:///var/run/docker.sock
      - --docker.domain=vno.nannal.com
      - --docker.watch=true
      - --docker.exposedbydefault=true
      - --acme.email=tortuga@nannal.com
      - --acme.storage=acme.json
      - --acme.entryPoint=https
      - --acme.onHostRule=true
      - --acme.httpchallenge.entrypoint=http
      - --api.dashboard=true


  portainer:
    container_name: admin
    image: portainer/portainer
    restart: unless-stopped
    volumes:
     - portainerconfig:/data
     - /var/run/docker.sock:/var/run/docker.sock
    labels:
      - traefik.port=9000


volumes:
  plexconfig:
  sonarrconfig:
  radarrconfig:
  lidarrconfig:
  jackettconfig:
  qbittorrentconfig:
  traefikconfig:
  portainerconfig:

  tv:
  films:
  music:
  transcode:
